---
image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .

# push-image:
#   stage: deploy
#   script:
#     - docker build --pull -t $CI_REGISTRY_IMAGE .
#     - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:latest
#     - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#     - docker push $CI_REGISTRY_IMAGE:latest
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
